Numpy for the lazy beginner!

In [4]:
import numpy as np
np.__version__

'1.12.1'

In [5]:
np.array([1,3,4,6,8,9])

array([1, 3, 4, 6, 8, 9])

In [6]:
np.array([.2,4,6,9,2.4])

array([ 0.2,  4. ,  6. ,  9. ,  2.4])

In [7]:
np.array([1,4,5,7,13], dtype='float32')

array([  1.,   4.,   5.,   7.,  13.], dtype=float32)

In [11]:
np.array([range(i, i+6) for i in (0,5,9)])

array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [ 9, 10, 11, 12, 13, 14]])

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones([3,4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.full([3,5], 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [24]:
np.arange(3)

array([0, 1, 2])

In [29]:
np.arange(0, 50, 7)

array([ 0,  7, 14, 21, 28, 35, 42, 49])

In [33]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [35]:
np.random.random([3,3])

array([[ 0.14114609,  0.98064775,  0.76761721],
       [ 0.70084094,  0.72742762,  0.86458364],
       [ 0.76275483,  0.43127351,  0.90287686]])

In [38]:
# Create a 3x3 array of normally distributed random values 
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[ 0.09860507, -0.03169911, -1.64011691],
       [ 1.58492936, -0.73763235, -1.44347721],
       [-0.55726846, -0.87956339,  1.09496824]])

In [40]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 1, 3],
       [5, 5, 0],
       [9, 7, 2]])

In [42]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [43]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that # memory location
np.empty(3)

array([ 1.,  1.,  1.])

Attributes of arrays:
Determining the size, shape, memory consumption, and data types of arrays

In [110]:
np.random.seed(0) #seed for reproducebility
x1 = np.random.randint(10, size=6) #One dimenion array
x2 = np.random.randint(10, size=(3,4)) #Two dimension array
x3 = np.random.randint(10, size=(2,4,6)) #Three dimension array

In [111]:
print(x3)
print('--------------')
print('Dimension:', x3.ndim) #the number of dimensions
print('shape:', x3.shape) #the size of each dimension
print('size:', x3.size) #the total size of the array
print('dtype:', x3.dtype) 
#itemsize: lists the size (in bytes) of each array element
#nbytes: lists the total size (in bytes) of the array
#In general, we expect that nbytes is equal to itemsize times size.
print('itemsize:', x3.itemsize)
print('Bytes:', x3.nbytes)

[[[8 1 5 9 8 9]
  [4 3 0 3 5 0]
  [2 3 8 1 3 3]
  [3 7 0 1 9 9]]

 [[0 4 7 3 2 7]
  [2 0 0 4 5 5]
  [6 8 4 1 4 9]
  [8 1 1 7 9 9]]]
--------------
Dimension: 3
shape: (2, 4, 6)
size: 48
dtype: int64
itemsize: 8
Bytes: 384


Indexing of arrays:
Getting and setting the value of individual array elements

In [112]:
print('x1:')
print(x1)
print(x1[0])
print(x1[-1])
print('--------------')
print('x2:')
print(x2)
print(x2[0,0])
print(x2[2,-2])

x1:
[5 0 3 3 7 9]
5
9
--------------
x2:
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
7


Slicing of arrays:
Getting and setting smaller subarrays within a larger array

In [113]:
##One-dimensional subarrays
print(x1[:5])
print(x1[5:])
print(x1[3:6])
print(x1[::2])
print(x1[0::3])

[5 0 3 3 7]
[9]
[3 7 9]
[5 3 7]
[5 3]


In [114]:
##Multidimensional subarrays
print('x2[:3, :4]')
print(x2[:3, :4])
print('--------------')
print('x2[:4, :3]')
print(x2[:4, :3])
print('--------------')
print('x2[:-1, :-1]')
print(x2[:-1, :-1])
print('--------------')
print('x2[::-1, ::-1]')
print(x2[::-1, ::-1])

x2[:3, :4]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
--------------
x2[:4, :3]
[[3 5 2]
 [7 6 8]
 [1 6 7]]
--------------
x2[:-1, :-1]
[[3 5 2]
 [7 6 8]]
--------------
x2[::-1, ::-1]
[[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]


In [115]:
##Accessing array rows and columns
print(x2[:, 0]) # first column of x2
print(x2[0, :]) # first row of x2

[3 7 1]
[3 5 2 4]


In [116]:
##Subarrays as no-copy views
print(x2)
print('--------------')
x2_sub = x2[:2, :2] 
print(x2_sub)
print('--------------')
x2_sub[0, 0] = 99 
print(x2_sub)
print('--------------')
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
--------------
[[3 5]
 [7 6]]
--------------
[[99  5]
 [ 7  6]]
--------------
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [117]:
##Creating copies of arrays
x2_sub_copy = x2[:2, :2].copy() 
print(x2_sub_copy)
print('--------------')
x2_sub_copy[0, 0] = 42 
print(x2_sub_copy)
print('--------------')
print(x2)

[[99  5]
 [ 7  6]]
--------------
[[42  5]
 [ 7  6]]
--------------
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Reshaping of arrays:
Changing the shape of a given array

In [119]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [121]:
x = np.array([1,2,3])
print(x)
print('--------------')
print(x.reshape([1,3]))
print('--------------')
print(x.reshape([3,1]))

[1 2 3]
--------------
[[1 2 3]]
--------------
[[1]
 [2]
 [3]]


Joining and splitting of arrays:
Combining multiple arrays into one, and splitting one array into many

In [124]:
x3 = np.array([1,2,3])
x4 = np.array([5,6,7])
np.concatenate([x3, x4])
x5 = np.array([9, 10, 11])
np.concatenate([x3, x4, x5])

array([ 1,  2,  3,  5,  6,  7,  9, 10, 11])

In [125]:
np.concatenate([x2,x2]) # concatenate along the first axis

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7],
       [99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [126]:
np.concatenate([x2,x2], axis = 1) # concatenate along the second axis (zero-indexed)

array([[99,  5,  2,  4, 99,  5,  2,  4],
       [ 7,  6,  8,  8,  7,  6,  8,  8],
       [ 1,  6,  7,  7,  1,  6,  7,  7]])

In [131]:
y1 = np.array([1,2,3])
y2 = np.array([[4,5,6], [7,8,9]])
np.vstack([y1,y2]) # vertically stack the arrays

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
y3 = np.array([[11],[12]])
np.hstack([y2,y3]) # horizontally stack the arrays

array([[ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [139]:
y4 = np.array([1,3,5,7,9,11,13,15])
z1, z2, z3 = np.split(y4, (4, 7)) #Split the array into multiple parts

print(z1)
print('--------------')
print(z2)
print('--------------')
print(z3)

[1 3 5 7]
--------------
[ 9 11 13]
--------------
[15]


In [148]:
grid = np.arange(16).reshape(4,4)
print(grid)
print('--------------')
grid1, grid2 = np.hsplit(grid, [2])
print(grid1)
print(grid2)
print('--------------')
grid3, grid4 = np.vsplit(grid, [2])
print(grid3)
print(grid4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
--------------
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
